export const data = [
    {
        employee: 'Oluaye Gbogbogbo',
        leaveType: 'Casual',
        startDate: 'Mar 02, 2020',
        Enddate: 'Mar 04, 2020',
        days: '3',
        description:  'To attending colleague\'s wedding',
        status: 'Active',
    },
    {
        employee: 'Oluaye Gbogbogbo',
        leaveType: 'Casual',
        startDate: 'Mar 02, 2020',
        Enddate: 'Mar 04, 2020',
        days: '3',
        description:  'To attending colleague\'s wedding',
        status: 'Active',
    },
    {
        employee: 'Oluaye Gbogbogbo',
        leaveType: 'Casual',
        startDate: 'Mar 02, 2020',
        Enddate: 'Mar 04, 2020',
        days: '3',
        description:  'To attending colleague\'s wedding',
        status: 'Active',
    },
    {
        employee: 'Oluaye Gbogbogbo',
        leaveType: 'Casual',
        startDate: 'Mar 02, 2020',
        Enddate: 'Mar 04, 2020',
        days: '3',
        description:  'To attending colleague\'s wedding',
        status: 'Active',
    },
    {
        employee: 'Oluaye Gbogbogbo',
        leaveType: 'Casual',
        startDate: 'Mar 02, 2020',
        Enddate: 'Mar 04, 2020',
        days: '3',
        description:  'To attending colleague\'s wedding',
        status: 'Active',
    },
    {
        employee: 'Oluaye Gbogbogbo',
        leaveType: 'Casual',
        startDate: 'Mar 02, 2020',
        Enddate: 'Mar 04, 2020',
        days: '3',
        description:  'To attending colleague\'s wedding',
        status: 'Active',
    },
    {
        employee: 'Oluaye Gbogbogbo',
        leaveType: 'Casual',
        startDate: 'Mar 02, 2020',
        Enddate: 'Mar 04, 2020',
        days: '3',
        description:  'To attending colleague\'s wedding',
        status: 'Active',
    },
    {
        employee: 'Oluaye Gbogbogbo',
        leaveType: 'Casual',
        startDate: 'Mar 02, 2020',
        Enddate: 'Mar 04, 2020',
        days: '3',
        description:  'To attending colleague\'s wedding',
        status: 'Active',
    },
    {
        employee: 'Oluaye Gbogbogbo',
        leaveType: 'Casual',
        startDate: 'Mar 02, 2020',
        Enddate: 'Mar 04, 2020',
        days: '3',
        description:  'To attending colleague\'s wedding',
        status: 'Active',
    },
    {
        employee: 'Oluaye Gbogbogbo',
        leaveType: 'Casual',
        startDate: 'Mar 02, 2020',
        Enddate: 'Mar 04, 2020',
        days: '3',
        description:  'To attending colleague\'s wedding',
        status: 'Active',
    },
    {
        employee: 'Oluaye Gbogbogbo',
        leaveType: 'Casual',
        startDate: 'Mar 02, 2020',
        Enddate: 'Mar 04, 2020',
        days: '3',
        description:  'To attending colleague\'s wedding',
        status: 'Active',
    },
    {
        employee: 'Oluaye Gbogbogbo',
        leaveType: 'Casual',
        startDate: 'Mar 02, 2020',
        Enddate: 'Mar 04, 2020',
        days: '3',
        description:  'To attending colleague\'s wedding',
        status: 'Active',
    },
    {
        employee: 'Oluaye Gbogbogbo',
        leaveType: 'Casual',
        startDate: 'Mar 02, 2020',
        Enddate: 'Mar 04, 2020',
        days: '3',
        description:  'To attending colleague\'s wedding',
        status: 'Active',
    },
    {
        employee: 'Oluaye Gbogbogbo',
        leaveType: 'Casual',
        startDate: 'Mar 02, 2020',
        Enddate: 'Mar 04, 2020',
        days: '3',
        description:  'To attending colleague\'s wedding',
        status: 'Active',
    },
    {
        employee: 'Oluaye Gbogbogbo',
        leaveType: 'Casual',
        startDate: 'Mar 02, 2020',
        Enddate: 'Mar 04, 2020',
        days: '3',
        description:  'To attending colleague\'s wedding',
        status: 'Active',
    },
    {
        employee: 'Oluaye Gbogbogbo',
        leaveType: 'Casual',
        startDate: 'Mar 02, 2020',
        Enddate: 'Mar 04, 2020',
        days: '3',
        description:  'To attending colleague\'s wedding',
        status: 'Active',
    },
]